print('Работа со словарями: ')
my_dict={'Andrew':1982,'Evgen':1995,'Roman':1990,'Petr':2002}
print('Мой словарь: ',my_dict)
print('Значение по существующему ключу: ',my_dict.get('Andrew','Такое имя отсутствует'))
print('Значение по отсутствующему ключу: ',my_dict.get('Fedor','Такое имя отсутствует'))
my_dict.update({'Max':2005,'Alex':2010})
print('Значение удаленной пары: ',my_dict.pop('Petr'))
print('Обновленный словарь',my_dict)
print('')
print('Работа со множествами: ')
my_set={1,1,3,3,2,4,5,6}
print('Мое множество: ',my_set)
my_set.update({7,8})
my_set.discard(2)
print('Измененное множество: ',my_set)